spring:
  application:
    name: backend-provider
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dazhou?useSSL=FALSE&serverTimezone=UTC
    username: root
    password: dazhou520
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  # redis 配置
  redis:
    port: 6379
    host: localhost
    database: 0
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 7529
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
dzapi:
  client:
    secret-key: dazhou
    access-key: abcdefgh
dubbo:
  application:
    name: dubbo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848
oss:
  accessKey: LTAI5tGBPNsnGPrFm1FbfMwW
  secret: DyughXRNJ1ryyzCQNjEVRORI2WoYku
  endpoint: oss-cn-guangzhou.aliyuncs.com
  bucketName: dazhou123
  url: https://dazhou123.oss-cn-guangzhou.aliyuncs.com/

alipay:
  appId: 9021000132663708
  appPrivateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC+8q+ZJ9y9Ep7DFAfZvFcJ+5dLH9nTm6VQ8RcXFm4Ox4PqliolgWF1JUBdQwqGPt7/ybxIDA6AcgF2gMwk6n/0gLC3n43aBfx6+tml1FxhJH72R3z59hmDvX3esQweN4a5e35gbXxfA6muJwCwMXqgswv3Tvokyz1twpUO4RIkUgsIX6f0MpEjD4zlxxM/C8lGKvvcViXWMfIeSlaY8tD2xEO4SZX6bfBUVNORwGf4j62jV3qu4aOMQnmzqd6E0birKsA/aasAKs2gdfA4qn8sxyFAjrjt13CP8veJi7HLZRmfqcVRZpefbC1WR+nd9nHXnjir9zIf37n0dhnmURmXAgMBAAECggEAXLafVmEJh/Bbj+LQ8QLGzD0Rt9NOQ7XGLifxiy9D3v826RdifXV1qZidyOq9WHN8eXwtZFoeTHWOikh9VstZt5EovO/Gw362mcvlE+Spui0rTE9nukKpHtNKI2+Zr65MRxFUSmO+yK+RmtKrPeG4ZgCppbn+MRFR0VJyZ5gW4/TtPOItJ72MVbQ33UbWjB02+H3w+1Dr11XXLxInxhthnYaTobUMV6oCfywiVSNH4NtwJaIzlROB42AI3oS53mUek9/RdXf+yuOcOyTMpNwkt3vBgeW1TVebqSObd+5Rq60q3HmrgODBxes4aP2ylLyxfCToaXgNd5Y58qhanqbQQQKBgQD+cFzY2aIHekhPQCTrCeWX9tAh/K4NlMXIetNNipVXkeuN4e5md8hIk5lK2MQ5eknkeSLiK15oVv8XcArfBHN2xRhEPRW/rD12Ifcuv24/yrUvyYwWsjsVhRJUqo7svG49yEU45W45wz9xbhX+4mFnzVJddZ/3sRS41TI2u7jf4QKBgQDAHpm7oKMOhT0zOYj+Y9xCJHnJ0FLZQModtWDjhBo8fnfjL0nIqlSLViGWwknImBpBF1Q+OPFZ/0o4WnChsA0PNxs39lAesjQIQLmx9R89n826z1e5XrAMvhX2LkXIBu/KeZ++asLnAXzNovFYF/Z2YCIhZNIuNx/BEZozMKIIdwKBgQCqMQSZ9HEiKVRG1nQbV4JgtLIhmb/ey73ETQwcGO+uJKf4PsDVf5fTnA70dqxCeh8FGVYRDMtYZaC5z7Ml2/dT4aBKvMVYcWCnLS8G8PtQ5kltzpXK9Kr6yQkq4u85QQ1IfDZ5SVYCgyxjtiw2UryuzzMh2rUG3EctH0Y4QDb4YQKBgQCMe1PKwTG6Qm9375BfBEJhEy8DBZQvTJL+mkyY0VYl+gxMUZ3QX8ymfnrdNICjb6VzB04Qma7SMjzhbDCD6qoCADek+jWn3ILzrfCbUjRf6WSUP11ULQrqpmyEsV1RYNEi60CGCqcuKAZMj+OOmScddDpA1Opj5OcRVH+/AsbZDQKBgATBt/mbV15HH8vhZNx4cV9mISPlwpMZZfIgEgblAGZn/qzk2tqfBlnp0PSeMvXkefFdJr4oOt+hmRStXMpN6LfIpCSeevrfJGdq0F5x/GrQykrQFYx4xyGV1XYXSjZ3hS6nEzW6VaxnlgBAF7ggWwxMg8XO/blpFso44wMLKyuj
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlu53iiyqQIadozGQ9Kd3RWy3r8digyjF3ahVN9tjfR996IYDjiCZ61hAEHRU2NnHZdXYcwMiDNuXV5xi5gu46XEC09IO46L0Ol0Zya+LNQe57c/sp/z1R4yVuj4jn/RLHaeLJ17BrJD1HPmKd59/SkIDiIcEDYEpxKi6ss4QVjWUw/PZxIBk4AR8r7H7qEgmgBGj/D0oURQ9MwdivyYXcKQ7Dhd+8jKYAzJB8mkdQOabpqvUNPLli/uUFasS+Eih12vlL8hJP8JzPms17XyA632I71FXIseCxtj6EAABtIXtn2aHn7upvws6jZ8Rn4lbpvYAwyNEWzT9KmEFviIgFQIDAQAB
  notifyUrl:  http://19f15090.r19.cpolar.top/api/alipay/notify

