server:
  port: 8090
spring:
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=source,dazhou
      routes:
        - id : api_interface
          uri: http://43.136.14.135:8123
          predicates:
            - Path=/api/**
  redis:
    port: 6379
    host: localhost
    database: 0

  application:
    name: gateways-consumer
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: HH:mm:ss:SSS
dubbo:
  application:
    name: dubbo-springboot-demo-provider
    protocol:
      name: dubbo
      port: -1
  registry:
    id: nacos-registry
    address: nacos://43.136.14.135:8848